# Generated by Django 3.2.8 on 2021-10-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mimsAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Holiday_name', models.CharField(max_length=100)),
                ('Holiday_date', models.CharField(max_length=100)),
                ('Holiday_status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Holidays',
            },
        ),
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'SuperAdmin',
            },
        ),
        migrations.DeleteModel(
            name='Hollydays',
        ),
    ]
