# Generated by Django 3.2.8 on 2021-11-01 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mimsAdmin', '0002_auto_20211028_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='departmentHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepHead_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'departmentHead',
            },
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department_name', models.CharField(max_length=100)),
                ('CourseDuration', models.IntegerField()),
                ('programName', models.CharField(max_length=100)),
                ('log_book', models.CharField(choices=[('reg', 'reg'), ('log1', 'log1'), ('log2', 'log2')], max_length=100)),
                ('AccreditationRenewalDate', models.DateField()),
                ('FirstYearStipend', models.CharField(max_length=100)),
                ('SecondYearStipend', models.CharField(max_length=100)),
                ('ThirdYearStipend', models.CharField(max_length=100)),
                ('FourYearStipend', models.CharField(blank=True, default='N/A', max_length=100)),
                ('FiveYearStipend', models.CharField(blank=True, default='N/A', max_length=100)),
                ('SixYearStipend', models.CharField(blank=True, default='N/A', max_length=100)),
                ('Department_Head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mimsAdmin.departmenthead')),
            ],
            options={
                'db_table': 'department',
            },
        ),
    ]
