# Generated by Django 3.2.8 on 2021-11-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mimsAdmin', '0003_department_departmenthead'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='dep_status',
            field=models.CharField(default='active', max_length=100),
        ),
        migrations.AlterField(
            model_name='department',
            name='log_book',
            field=models.CharField(max_length=100),
        ),
    ]
