# Generated by Django 3.2.8 on 2021-11-03 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mimsAdmin', '0005_course_experience_faculty_professionalqualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='PersonOfExperience',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mimsAdmin.faculty'),
            preserve_default=False,
        ),
    ]
