# Generated by Django 3.2.8 on 2021-11-05 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mimsAdmin', '0006_experience_personofexperience'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='faculty',
            table='Faculty',
        ),
    ]
