# Generated by Django 3.2.8 on 2021-11-05 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mimsAdmin', '0007_alter_faculty_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='FacultyDepartment',
        ),
        migrations.RemoveField(
            model_name='professionalqualification',
            name='PersonOfQualification',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='faculty',
        ),
        migrations.DeleteModel(
            name='ProfessionalQualification',
        ),
    ]
