# Generated by Django 3.2.8 on 2021-11-05 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mimsAdmin', '0008_auto_20211105_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FacultyName', models.CharField(max_length=100)),
                ('Designation', models.CharField(max_length=100)),
                ('DateOfBirth', models.DateField()),
                ('PanNumber', models.CharField(max_length=100)),
                ('FacultyEligibility', models.CharField(max_length=500)),
                ('PresentResidential', models.CharField(max_length=500)),
                ('PermenentResidential', models.CharField(max_length=500)),
                ('Photo', models.ImageField(upload_to='Faculty_img')),
                ('IdPhoto', models.ImageField(upload_to='Faculty_img')),
                ('IdNumber', models.CharField(max_length=100)),
                ('IssuingAuthority', models.CharField(max_length=100)),
                ('Tele', models.CharField(max_length=100)),
                ('Mobile', models.CharField(max_length=100)),
                ('MobileAlt', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('FacultyDepartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mimsAdmin.department')),
            ],
            options={
                'db_table': 'Faculty',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseName', models.CharField(max_length=100)),
                ('SpecializationArea', models.CharField(max_length=100)),
                ('YearOfPassing', models.CharField(max_length=100)),
                ('QualificationRegNo', models.CharField(max_length=100)),
                ('MedicalCouncilName', models.CharField(max_length=100)),
                ('RegistrationValidUpto', models.CharField(max_length=100)),
                ('Document', models.FileField(upload_to='Documents/ProfessionalQualification')),
                ('PersonOfQualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mimsAdmin.faculty')),
            ],
            options={
                'db_table': 'ProfessionalQualification',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PostPGExperience', models.IntegerField()),
                ('PeriodOfEmployment', models.CharField(max_length=100)),
                ('From_PeriodOfEmployment', models.DateField()),
                ('To_PeriodOfEmployment', models.DateField()),
                ('DesignationHeld', models.CharField(max_length=100)),
                ('HospitalInstitutionCityState', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('EmploymentStatus', models.CharField(max_length=100)),
                ('HoursSpentPerDay', models.IntegerField()),
                ('WhetherAssociatedDNB_FND', models.CharField(max_length=100)),
                ('PersonOfExperience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mimsAdmin.faculty')),
            ],
            options={
                'db_table': 'Experience',
            },
        ),
    ]
