# Generated by Django 3.2.8 on 2021-11-05 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mimsAdmin', '0009_experience_faculty_professionalqualification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='FacultyDepartment',
        ),
        migrations.RemoveField(
            model_name='professionalqualification',
            name='PersonOfQualification',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='ProfessionalQualification',
        ),
    ]
