# Generated by Django 3.2.8 on 2021-11-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mimsAdmin', '0012_professionalqualification_nameofcollege'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleName', models.CharField(max_length=100)),
                ('roleStatus', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Role',
            },
        ),
    ]
