# Generated by Django 3.2.8 on 2021-11-08 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mimsAdmin', '0013_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ParentPath', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'Parent',
            },
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathName', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mimsAdmin.parentpath')),
            ],
            options={
                'db_table': 'Path',
            },
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PathForPermission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mimsAdmin.path')),
                ('PermissionOfRole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mimsAdmin.role')),
            ],
            options={
                'db_table': 'Permissions',
                'unique_together': {('PermissionOfRole', 'PathForPermission')},
            },
        ),
    ]
