# Generated by Django 3.2.8 on 2021-11-09 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mimsAdmin', '0015_auto_20211108_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='Path',
            field=models.CharField(blank=True, default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='path',
            name='SortOrder',
            field=models.IntegerField(blank=True),
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('userDepartMent', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('userRole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mimsAdmin.role')),
            ],
            options={
                'db_table': 'UserTable',
            },
        ),
    ]
