# Generated by Django 3.2.8 on 2021-11-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mimsAdmin', '0017_auto_20211110_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='conferenceOrganizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Organizezr_Name', models.CharField(max_length=100)),
                ('Organizezr_status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'conferenceOrganizer',
            },
        ),
    ]
