# Generated by Django 3.2.8 on 2021-11-15 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mimsAdmin', '0018_conferenceorganizer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='conferenceOrganizer',
            new_name='ConferenceOrganizerTable',
        ),
        migrations.AlterModelTable(
            name='conferenceorganizertable',
            table='ConferenceOrganizerTable',
        ),
    ]
