# Generated by Django 3.2.8 on 2021-11-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mimsAdmin', '0019_auto_20211115_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferenceorganizertable',
            name='Organizezr_status',
            field=models.CharField(choices=[('active', 'Activate'), ('inactive', 'Inactivate')], max_length=100),
        ),
        migrations.CreateModel(
            name='BooksTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Books_Name', models.CharField(max_length=100)),
                ('Auther_Name', models.CharField(max_length=100)),
                ('Books_availability', models.IntegerField()),
                ('Books_Edition', models.CharField(max_length=100)),
                ('Short_Summary', models.TextField()),
                ('Books_status', models.CharField(default='active', max_length=100)),
                ('Department', models.ManyToManyField(to='mimsAdmin.department', verbose_name='list of department')),
            ],
            options={
                'db_table': 'BooksTable',
                'unique_together': {('Books_Name', 'Auther_Name')},
            },
        ),
    ]
