# Generated by Django 3.2.8 on 2021-11-16 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mimsAdmin', '0021_auto_20211116_1615'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogMasterTable',
        ),
        migrations.DeleteModel(
            name='tableHeads',
        ),
    ]
