# Generated by Django 3.2.8 on 2021-11-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mimsAdmin', '0024_auto_20211117_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationtable',
            name='Date',
            field=models.DateField(),
        ),
    ]
