# Generated by Django 3.2.8 on 2021-11-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mimsAdmin', '0030_alter_publicationtable_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Journal_name', models.CharField(max_length=100)),
                ('Edition', models.CharField(max_length=100)),
                ('Published_Date', models.DateField()),
                ('Publisher_name', models.CharField(max_length=100)),
                ('Journal_Type', models.CharField(choices=[('National', 'National'), ('International', 'International')], max_length=100)),
                ('Short_Summary', models.TextField()),
                ('status', models.CharField(choices=[('Activate', 'active'), ('Inactivate', 'inactive')], max_length=100)),
                ('Journal_department', models.ManyToManyField(to='mimsAdmin.department', verbose_name='Department')),
            ],
            options={
                'db_table': 'Journals',
                'unique_together': {('Journal_name', 'Edition', 'Published_Date')},
            },
        ),
    ]
