# Generated by Django 3.2.8 on 2021-11-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mimsAdmin', '0031_journalstable'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Form_name', models.CharField(max_length=100)),
                ('Form', models.FileField(upload_to='Documents/form')),
                ('status', models.CharField(choices=[('active', 'Activate'), ('inactive', 'Inactivate')], max_length=100)),
            ],
            options={
                'db_table': 'form',
            },
        ),
        migrations.AlterField(
            model_name='journalstable',
            name='status',
            field=models.CharField(choices=[('active', 'Activate'), ('inactive', 'Inactivate')], max_length=100),
        ),
    ]
